### ISSUE TITLE
UpDownload: application crashes

### ISSUE THREAD

**Issue by chStaiger** [chStaiger/iBridges-Gui#25] opened 2022-10-26 20:08 UTC
in the tab UpDownload:
When diffs are calculated or data is transferred, the app crashes when user clicks on "cancel"

**Comment by jpmcfarland** [comment] 2023-03-15 09:08
Issue rijksuniversiteit-groningen#73 is a duplicate of this and reference to this Issue above is actually Issue rijksuniversiteit-groningen#25.

**Closed** 2024-06-06 13:45 UTC
Labels: bug
